### ISSUE TITLE
How to stop mock

### ISSUE THREAD

**Issue by vitaly87** [testphony/codeceptjs-httpMock#1]
Hi, 
I am not sure if this what I need but basically I am looking for changing only part of response and also be able to stop the mock when I want .
Is this possible ?

**Comment by APshenkin** [comment]
Hi!

No, this helper doesn't provide proxy to original recource, so you should describe logic for complete response

This mock creates a tiny http server with decribed routes and described logic of responses. Before each test list of routes will be cleared, so you should recreate routes or paste them in `Before`  section
